### ISSUE TITLE
custom sort

### ISSUE THREAD

**Issue by timelyportfolio** [cmpolis/datacomb#18]
I think there is a way to custom sort for instance for dates or discrete numeric, but I cannot find the magic combination.  Are there any examples/demos that I am missing?  Thanks.

**Comment by cmpolis** [comment]
This functionality isn't built in at the moment(but shouldn't be too difficult - I'll work on it). For dates, you can use the epoch`eg: (new Date()).valueOf()` (or some other numeric representation of dates) and specify the column format function as a function to convert that int value into a readable string. 

```javascript
// fair warning: haven't tested this, but it *should* work
var dateFormat = d3.time.format("%Y-%m-%d");

// column defenitions...
{
  label: 'Birthday',
  accessor: function(row) { return dateFormat.parse(row.birthday).valueOf() },
  format: function(d) { return dateFormat(new Date(d)); },
}
```

... that being said... this looks a bit hacky and maybe dates should be a first class `column.type`, there are other display things that this will not handle eg: filters and axes will show epoch values(big, uninformative #)

**Comment by cmpolis** [comment]
put in a quick update for discrete col ordering:
```javascript
{
  label: 'Pos',
  accessor: 'pos',
  type: 'discrete',
  sortOrder: 'PG SG SF PF C'.split(' ')
},
```
